version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "robot@users.noreply.github.com"
            git config --global user.name "website deploy script"
            yarn install && yarn build
            echo '------'
            ls && cd /home/circleci && ls
            echo '------'
            git clone git@github.com:gatsbyci/gatsbyci.github.io.git gatsbyci
            rm -rf ./gatsbyci/* && ls ./gatsbyci
            echo '------'
            cp -rf ./project/public/* ./gatsbyci && ls ./gatsbyci
            echo '------'
            cd ./gatsbyci && git add . && git commit -a -m 'org build version' && git push

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
